<?xml version="1.0"?>
<!DOCTYPE PCT-Data PUBLIC "-//NCBI//NCBI PCTools/EN" "http://pubchem.ncbi.nlm.nih.gov/pug/pug.dtd">
<PCT-Data>
  <PCT-Data_input>
    <PCT-InputData>
      <PCT-InputData_download>
        <PCT-Download>
          <PCT-Download_uids>
            <PCT-QueryUids>
              <PCT-QueryUids_ids>
                <PCT-ID-List>
                  <PCT-ID-List_db>pccompound</PCT-ID-List_db>
                  <PCT-ID-List_uids>
                    <PCT-ID-List_uids_E>4122</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3385</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>703492</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>555820</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>700989</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>792340</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7996519</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189069</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189070</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189071</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189072</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189073</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189074</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189075</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189076</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189077</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189078</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189079</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189080</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189081</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189082</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189083</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189084</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189085</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189086</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189087</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189088</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189089</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189090</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189091</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189092</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189093</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189094</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189095</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189096</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189097</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189098</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189099</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189100</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189101</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189102</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189103</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189104</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189105</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189106</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>122189107</PCT-ID-List_uids_E>
                  </PCT-ID-List_uids>
                </PCT-ID-List>
              </PCT-QueryUids_ids>
            </PCT-QueryUids>
          </PCT-Download_uids>
          <PCT-Download_format value="smiles"/>
          <PCT-Download_compression value="gzip"/>
          <PCT-Download_use-3d value="false"/>
        </PCT-Download>
      </PCT-InputData_download>
    </PCT-InputData>
  </PCT-Data_input>
</PCT-Data>
