<?xml version="1.0"?>
<!DOCTYPE PCT-Data PUBLIC "-//NCBI//NCBI PCTools/EN" "http://pubchem.ncbi.nlm.nih.gov/pug/pug.dtd">
<PCT-Data>
  <PCT-Data_input>
    <PCT-InputData>
      <PCT-InputData_download>
        <PCT-Download>
          <PCT-Download_uids>
            <PCT-QueryUids>
              <PCT-QueryUids_ids>
                <PCT-ID-List>
                  <PCT-ID-List_db>pccompound</PCT-ID-List_db>
                  <PCT-ID-List_uids>
                    <PCT-ID-List_uids_E>460612</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>26879</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>53305112</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>53304962</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>53305115</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>53305116</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71597546</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71597548</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>66561162</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710847</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710848</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710849</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710850</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710851</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710852</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710853</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710854</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710855</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710856</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710857</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710858</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710859</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710860</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710861</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710862</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710863</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710864</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710865</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710866</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710867</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710868</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710869</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710870</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710871</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710872</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710873</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710874</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118710875</PCT-ID-List_uids_E>
                  </PCT-ID-List_uids>
                </PCT-ID-List>
              </PCT-QueryUids_ids>
            </PCT-QueryUids>
          </PCT-Download_uids>
          <PCT-Download_format value="smiles"/>
          <PCT-Download_compression value="gzip"/>
          <PCT-Download_use-3d value="false"/>
        </PCT-Download>
      </PCT-InputData_download>
    </PCT-InputData>
  </PCT-Data_input>
</PCT-Data>
