<?xml version="1.0"?>
<!DOCTYPE PCT-Data PUBLIC "-//NCBI//NCBI PCTools/EN" "http://pubchem.ncbi.nlm.nih.gov/pug/pug.dtd">
<PCT-Data>
  <PCT-Data_input>
    <PCT-InputData>
      <PCT-InputData_download>
        <PCT-Download>
          <PCT-Download_uids>
            <PCT-QueryUids>
              <PCT-QueryUids_ids>
                <PCT-ID-List>
                  <PCT-ID-List_db>pccompound</PCT-ID-List_db>
                  <PCT-ID-List_uids>
                    <PCT-ID-List_uids_E>94391</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3385</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118719412</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118719413</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118719414</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118719415</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118719416</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724735</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724736</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724737</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724738</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724739</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724740</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724741</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724742</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724743</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724744</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724745</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724746</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724747</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724748</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724749</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724750</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724751</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724752</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724753</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724754</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724755</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724756</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724757</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724758</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724759</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724760</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>118724761</PCT-ID-List_uids_E>
                  </PCT-ID-List_uids>
                </PCT-ID-List>
              </PCT-QueryUids_ids>
            </PCT-QueryUids>
          </PCT-Download_uids>
          <PCT-Download_format value="smiles"/>
          <PCT-Download_compression value="gzip"/>
          <PCT-Download_use-3d value="false"/>
        </PCT-Download>
      </PCT-InputData_download>
    </PCT-InputData>
  </PCT-Data_input>
</PCT-Data>
