<?xml version="1.0"?>
<!DOCTYPE PCT-Data PUBLIC "-//NCBI//NCBI PCTools/EN" "http://pubchem.ncbi.nlm.nih.gov/pug/pug.dtd">
<PCT-Data>
  <PCT-Data_input>
    <PCT-InputData>
      <PCT-InputData_download>
        <PCT-Download>
          <PCT-Download_uids>
            <PCT-QueryUids>
              <PCT-QueryUids_ids>
                <PCT-ID-List>
                  <PCT-ID-List_db>pccompound</PCT-ID-List_db>
                  <PCT-ID-List_uids>
                    <PCT-ID-List_uids_E>2756</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5325</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2719</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>774</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>50287</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3634</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3033637</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4046</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2247</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13342</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5702160</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>359323</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>64927</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>164435</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>65999</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>79729</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2466</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>441336</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>14957</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>74989</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4747</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9820</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9410</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>135565707</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>90454</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6239</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>452550</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2846972</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2903301</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2914547</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2846340</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>114771</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2903171</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2903111</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2903255</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>32798</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73334</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5702295</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>137630036</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10236521</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>21127119</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>137630035</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11957564</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>53317379</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>52933525</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>52933524</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>52933526</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>52933529</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>52933527</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>135980484</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2870785</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>53317761</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>53317762</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>53317763</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>24101046</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>52933523</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>52933528</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>52933281</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>52933530</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>52934003</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>23763528</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3040199</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>53320389</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>52934002</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>23741730</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2903181</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2880627</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>53320390</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>19895458</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134778</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>52934004</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>53321699</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>53321700</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>18974811</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>784035</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>52933522</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>135980482</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>53324380</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2846415</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>161104</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>53325241</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>52933280</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>135980483</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>17159289</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3792364</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>784405</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>52933283</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70682892</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5978</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>47909</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6917864</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10221470</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16211610</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>656862</PCT-ID-List_uids_E>
                  </PCT-ID-List_uids>
                </PCT-ID-List>
              </PCT-QueryUids_ids>
            </PCT-QueryUids>
          </PCT-Download_uids>
          <PCT-Download_format value="smiles"/>
          <PCT-Download_compression value="gzip"/>
          <PCT-Download_use-3d value="false"/>
        </PCT-Download>
      </PCT-InputData_download>
    </PCT-InputData>
  </PCT-Data_input>
</PCT-Data>
