<?xml version="1.0"?>
<!DOCTYPE PCT-Data PUBLIC "-//NCBI//NCBI PCTools/EN" "http://pubchem.ncbi.nlm.nih.gov/pug/pug.dtd">
<PCT-Data>
  <PCT-Data_input>
    <PCT-InputData>
      <PCT-InputData_download>
        <PCT-Download>
          <PCT-Download_uids>
            <PCT-QueryUids>
              <PCT-QueryUids_ids>
                <PCT-ID-List>
                  <PCT-ID-List_db>pccompound</PCT-ID-List_db>
                  <PCT-ID-List_uids>
                    <PCT-ID-List_uids_E>3385</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>137317282</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>137317283</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>137317290</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130060</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>137317292</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>137317294</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130205</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130261</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130299</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>137317299</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>137317300</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>137317301</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130400</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130421</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>137317302</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>137317306</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130720</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130786</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130788</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130840</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130918</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>137317312</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>137317313</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130955</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>137317318</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>137317318</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134131019</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134131091</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>137317320</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134131194</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134131233</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>137317324</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134131402</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134131499</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>137317332</PCT-ID-List_uids_E>
                  </PCT-ID-List_uids>
                </PCT-ID-List>
              </PCT-QueryUids_ids>
            </PCT-QueryUids>
          </PCT-Download_uids>
          <PCT-Download_format value="smiles"/>
          <PCT-Download_compression value="gzip"/>
          <PCT-Download_use-3d value="false"/>
        </PCT-Download>
      </PCT-InputData_download>
    </PCT-InputData>
  </PCT-Data_input>
</PCT-Data>
