<?xml version="1.0"?>
<!DOCTYPE PCT-Data PUBLIC "-//NCBI//NCBI PCTools/EN" "http://pubchem.ncbi.nlm.nih.gov/pug/pug.dtd">
<PCT-Data>
  <PCT-Data_input>
    <PCT-InputData>
      <PCT-InputData_download>
        <PCT-Download>
          <PCT-Download_uids>
            <PCT-QueryUids>
              <PCT-QueryUids_ids>
                <PCT-ID-List>
                  <PCT-ID-List_db>pccompound</PCT-ID-List_db>
                  <PCT-ID-List_uids>
                    <PCT-ID-List_uids_E>7168</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>202396</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>280160</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>95833</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>242888</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4785981</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>252604</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>78503</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2306549</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4155370</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>763883</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>531997</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>765344</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>853652</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8362873</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4410225</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>532001</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>825431</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>966016</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>531963</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>785556</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>793787</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>966007</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>759456</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>531967</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>794474</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>966762</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>295105</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>275109</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>705916</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>722390</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>40561022</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1369981</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3582371</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>646891</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3532749</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2274358</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>532008</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>790350</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>242891</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7688881</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1380774</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>532011</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2876965</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5157369</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4411436</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2665137</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>823475</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>793815</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>22336590</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>105534577</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3893537</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1357063</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>790108</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>803381</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>531839</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>803364</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>835330</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7688876</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1019232</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>531843</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>790127</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1277478</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2635646</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2635656</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8713816</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2635677</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2635672</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2635673</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7688839</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>24203363</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9411125</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>25341987</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>37239285</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>615665</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1241284</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>26517719</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1230047</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7741668</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>702115</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>669705</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>870401</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3570273</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1371056</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>724086</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1126377</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3095619</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>724089</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>675271</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1092365</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>795014</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7409078</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13016199</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>54790805</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>17085988</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>17086057</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>135564192</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>105534085</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>135564193</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>135564194</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2990927</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1301291</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2985449</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2111762</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2987322</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2987564</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7741633</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>679012</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>47112445</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3120393</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>19400</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>135564195</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>135564196</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>135564197</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>135564198</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>135564199</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>730377</PCT-ID-List_uids_E>
                  </PCT-ID-List_uids>
                </PCT-ID-List>
              </PCT-QueryUids_ids>
            </PCT-QueryUids>
          </PCT-Download_uids>
          <PCT-Download_format value="smiles"/>
          <PCT-Download_compression value="gzip"/>
          <PCT-Download_use-3d value="false"/>
        </PCT-Download>
      </PCT-InputData_download>
    </PCT-InputData>
  </PCT-Data_input>
</PCT-Data>
