<?xml version="1.0"?>
<!DOCTYPE PCT-Data PUBLIC "-//NCBI//NCBI PCTools/EN" "http://pubchem.ncbi.nlm.nih.gov/pug/pug.dtd">
<PCT-Data>
  <PCT-Data_input>
    <PCT-InputData>
      <PCT-InputData_download>
        <PCT-Download>
          <PCT-Download_uids>
            <PCT-QueryUids>
              <PCT-QueryUids_ids>
                <PCT-ID-List>
                  <PCT-ID-List_db>pccompound</PCT-ID-List_db>
                  <PCT-ID-List_uids>
                    <PCT-ID-List_uids_E>5351344</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31703</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>36314</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5978</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127048399</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127048400</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>21850299</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127048401</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127048402</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127048403</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127049070</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127049384</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127049385</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127051876</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127051877</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127051878</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127051879</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127051880</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127051881</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127052200</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127052509</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>21850214</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127052790</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127052791</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127052792</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>21850283</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127052793</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127052794</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127052795</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127052796</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127052797</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127052798</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127052799</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127052800</PCT-ID-List_uids_E>
                  </PCT-ID-List_uids>
                </PCT-ID-List>
              </PCT-QueryUids_ids>
            </PCT-QueryUids>
          </PCT-Download_uids>
          <PCT-Download_format value="smiles"/>
          <PCT-Download_compression value="gzip"/>
          <PCT-Download_use-3d value="false"/>
        </PCT-Download>
      </PCT-InputData_download>
    </PCT-InputData>
  </PCT-Data_input>
</PCT-Data>
