<?xml version="1.0"?>
<!DOCTYPE PCT-Data PUBLIC "-//NCBI//NCBI PCTools/EN" "http://pubchem.ncbi.nlm.nih.gov/pug/pug.dtd">
<PCT-Data>
  <PCT-Data_input>
    <PCT-InputData>
      <PCT-InputData_download>
        <PCT-Download>
          <PCT-Download_uids>
            <PCT-QueryUids>
              <PCT-QueryUids_ids>
                <PCT-ID-List>
                  <PCT-ID-List_db>pccompound</PCT-ID-List_db>
                  <PCT-ID-List_uids>
                    <PCT-ID-List_uids_E>5351344</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134129879</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134129890</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134129896</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134129961</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134129968</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134129978</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130065</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130174</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130191</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130209</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>132819944</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130221</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130290</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130368</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130395</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130406</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130424</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130449</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130597</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130621</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130764</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130779</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130838</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>132819942</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130887</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130931</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130946</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134130951</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>132819941</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134131106</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134131264</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134131386</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134131398</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134131400</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134131582</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>132819940</PCT-ID-List_uids_E>
                  </PCT-ID-List_uids>
                </PCT-ID-List>
              </PCT-QueryUids_ids>
            </PCT-QueryUids>
          </PCT-Download_uids>
          <PCT-Download_format value="smiles"/>
          <PCT-Download_compression value="gzip"/>
          <PCT-Download_use-3d value="false"/>
        </PCT-Download>
      </PCT-InputData_download>
    </PCT-InputData>
  </PCT-Data_input>
</PCT-Data>
