<?xml version="1.0"?>
<!DOCTYPE PCT-Data PUBLIC "-//NCBI//NCBI PCTools/EN" "http://pubchem.ncbi.nlm.nih.gov/pug/pug.dtd">
<PCT-Data>
  <PCT-Data_input>
    <PCT-InputData>
      <PCT-InputData_download>
        <PCT-Download>
          <PCT-Download_uids>
            <PCT-QueryUids>
              <PCT-QueryUids_ids>
                <PCT-ID-List>
                  <PCT-ID-List_db>pccompound</PCT-ID-List_db>
                  <PCT-ID-List_uids>
                    <PCT-ID-List_uids_E>26041</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5281576</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5281575</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5280795</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7529</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8419</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>62969</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10215</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>61186</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8061</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6440940</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>66449</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>33133</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5590</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>18725</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8783</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>17142</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7540</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11776</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5569</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6535</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6420</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6421</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13931</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5541</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>638015</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>641240</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>638186</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1140</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8030</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3032791</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>864</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>700999</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2734117</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8404</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2723754</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8197</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>28803</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>28803</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8326</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31373</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12443</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>62753</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6618</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16043</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6410</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6410</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7489</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>86102</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>32793</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>18360</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11966</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>24314</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>61207</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>61247</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7172</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5340</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5987</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5329</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5320</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8062</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16220118</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>23668192</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>23668193</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3423265</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>516919</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3423265</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>108005</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>108005</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>23668194</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>516902</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>23668195</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>23668195</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31553</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11972286</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>60934</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>26323</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>18056</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>135398743</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10168</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>445154</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1057</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31423</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67172</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6988</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7724</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6269</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7390</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7381</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>228987</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7175</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>92629</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1030</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>15286</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5994</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>36242</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9076</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>24502</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13539</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>17231</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7473</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7494</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>17549</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8502</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7487</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11505</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9473</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8438</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10129</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>15965</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>24819</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>15158</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1004</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3610</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>676454</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>14090</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>19188</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>24744</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537507</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7666</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8615</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>995</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31070</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8813</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>19042</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11855</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>36159</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>36159</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>66041</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7810</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6318</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7805</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>15277</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>991</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7732</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31244</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>403</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31230</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>978</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8479</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>19266</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6625</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3035</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1752</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5281034</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7242</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8373</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6984</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>967</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>157882</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7243</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7203</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1318</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6944</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11888</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>27054</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11921</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11875</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11087</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11876</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6946</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11346</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>460</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10377</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5371728</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>445639</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>102484</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>379</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537506</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16640</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>14906</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7977</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6921</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8374</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7236</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7000</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5801</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6926</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7013</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8003</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5281249</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8141</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5930</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>25711</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11954</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7483</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5935</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>41684</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7573</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13032</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16637</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10236</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4485</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>62390</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10313</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8872</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4463</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7098</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6637</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7670</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>28594</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>30231</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>64142</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>18510</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6633</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>17049</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>263</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8846</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7684</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8443</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10843</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8041</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7589</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>80365</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7472</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8749</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6228</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7120</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6828</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7490</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8097</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13101</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4276</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2478</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7929</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6753</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12104</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12120</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>14236</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>20393</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16653</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11137</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12078</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8495</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8497</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12576</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7423</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8494</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5281567</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16907</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7455</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>15294</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7127</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>104827</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>22772</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6570</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6010</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>637759</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4133</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11167</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12228</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>20686</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10797</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3672772</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7747</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7150</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8635</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7294</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4115</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12251</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5366546</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31368</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6595</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>329983</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>896</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6279</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7452</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7933</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7374</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>447</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7932</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11560</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10824</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11568</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7604</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8474</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8369</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2724411</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10638</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5280934</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5280450</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6549</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>22456</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>22456</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>17163</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8192</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3893</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>439280</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>299</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5281565</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5807</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>62553</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13551</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6364</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>19920</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7915</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7916</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10453</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>169132</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>108242</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>18502</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7352</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8053</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5273467</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31276</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3712</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>24812</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>795</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537505</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>24846</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>91649</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1309</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1550884</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8119</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3562</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3552</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6450278</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6439929</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7860</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7837</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>753</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3485</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1549026</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13521</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12170</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5325504</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>637930</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7671</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>713</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3397</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6446</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>24603</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10008</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9154</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7611</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>25914</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5365543</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8133</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12375</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>701</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>15394</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6113</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6371716</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>81530</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6877</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8821</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12301</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>14710</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3278</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537504</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12968</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3220</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>68589</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5281771</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10866</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2537</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>66666</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>19283</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8033</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13816</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537503</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537503</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7595</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8561</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8559</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16316</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7820</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11317</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70452</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12232</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>82728</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>14242</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12329</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10660</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12734</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7912</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>229852</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>98356</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7586</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537502</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8210</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>19996</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6781</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6534</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7766</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>18283</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6492</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7582</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7582</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6641</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3039</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>18617</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12433</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>74189</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>75969</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9217</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8689</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2723951</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8344</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5273621</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>23668196</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537501</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7044</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>159055</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10788</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>62770</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>18283</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>83511</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6731</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537500</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>22420</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7298</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9253</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>18502</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6197</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6197</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9246</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13610</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7954</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>969516</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6629</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73773</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>447466</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2879</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>460</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6167</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6167</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>92884</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>638011</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5356785</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2767</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>643833</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10900</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>637511</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>637511</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537499</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5281764</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10208</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537498</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537497</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6397</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537496</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537496</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9552079</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5993</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8816</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7335</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7438</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2576</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5943</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6348</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>25429</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8606</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8124</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>14782</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537495</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8855</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7798</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>121752</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>24433</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5324278</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>114809</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>542762</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7961</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>61591</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31253</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537494</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7913</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2286</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6623</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>82917</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8147</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7944</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1491</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5284459</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8842</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12456</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5963</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>17355</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10867</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8363</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>60999</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10387</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7368</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7367</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7222</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>95416</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9158</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6796</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9128</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9153</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5798</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8478</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7369</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7371</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>241</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>28780</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10771</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10316</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5462814</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>447043</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537493</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2202</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537492</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>24639</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>22985</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11065</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16230</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>261491</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6654</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11080</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7407</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5354896</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>51</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10758</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>444913</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7498</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7411</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1549517</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>61410</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7841</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>24116</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11584</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>15588</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9568700</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>443939</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537491</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6579</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2244</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537490</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8035</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1988</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7592</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7918</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7765</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11074431</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5375199</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11767</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2723598</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1923</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11927</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7050</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7092</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>15630</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537489</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>22463</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11356</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2355</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>76063</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6035</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4075</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>17818</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>22574</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5354284</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>80642</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>237332</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537488</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11604</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6969</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>230976</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3543259</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>21208</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>38764</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13195</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7319</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8390</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6978</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12748</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7331</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5288209</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9147</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7394</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8462</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9809</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6979</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12088</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7101</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6128</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6128</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>22586</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11432</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7570</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6625</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>15660</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>76985</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6259976</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8469</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5324707</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7386</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>18370</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>21575</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7546</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8428</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7421</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7062</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10963</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10963</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6894</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11241</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16449</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>76583</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>15206</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12308</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7375</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>61527</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7949</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7948</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11571</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5811</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12281</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7248</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11883</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7249</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7607</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7258</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7443</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5817</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>22710</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10332</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>25608</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11859</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>88365</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>95116</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8413</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8411</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16918</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8362</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>41206</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6618</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>759280</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>18635</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>21499</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7521</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6923</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6732</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5364360</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>33528</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12252</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8407</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6829</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7621</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7301</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6559</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10704</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16097</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7441</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16096</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11783</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12512</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6028739</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7745</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>707035</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>28503</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11671</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9808</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>30541</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7719</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7719</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>22571</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>17162</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7636</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8697</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31241</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7211</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8076</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5362708</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13594</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7056</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6996</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16004</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11673</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8133</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6358</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16329</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>15752</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>32346</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2155</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7015</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8706</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13624</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11937</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>22704</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7192</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>34757</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>34665</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>40301</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7264</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>15132</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>21622</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7265</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>29872</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3894848</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7385</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>520108</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>14286</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>15008</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6896</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13205</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7040</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11335</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6899</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>78392</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5758</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6737</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7259</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8031</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7267</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>66</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5784</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7262</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7250</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11443</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12262</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>637564</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10226</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1491</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67967</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9709</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11899</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5787</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11123</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5283349</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>61286</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16180</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>25607</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>29228</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>113124</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7271</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6983</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>21058</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6893</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11761</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6589</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10687</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>20039</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16659</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11334</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>18555</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5765</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6565</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12018</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11746</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13618</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13619</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13636</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8330</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>27582</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>28697</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13428</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7329</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6403</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>19871</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11684</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7791</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11660</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>20167</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>18692</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>20250</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>95170</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>37034</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>155166</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>17111</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>174223</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>62725</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8196</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8004</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8125</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12589</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13432</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16932</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12574</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11597</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6264</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7003</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7849</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11750</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6436079</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3378440</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>25644</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16402</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11803</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6974</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>17046</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8064</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3083585</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10423</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7594</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11818</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7908</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7426</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6991</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6672</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>171660</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10868</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>24726</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7289</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>637892</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7950</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>18604</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>23741</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16993</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13586</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7440</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6739</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8981</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8981</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>21660</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>69317</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4649906</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7270</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6895</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12468</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7046</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12463</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>15560</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7657</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11245</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6588</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>61179</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8394</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5371084</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>18728</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>641245</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>106729</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11742</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6782</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>14855</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6997</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5753</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8554</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>66494</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67174</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7577</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2482</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11328</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>853433</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4632</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5280443</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5284643</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6013</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5994</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10635</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13089</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6984</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>15730</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5281708</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5280961</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2999413</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>24066</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3121</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5578</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5565</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5284626</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5333</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5328</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>37542</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>445354</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>441074</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4992</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7175</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4909</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4064</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>896</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73339</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>612</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>460</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2724385</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>135398739</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2788</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>14749</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2720</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2662</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5361202</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2554</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2391</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5280965</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>135401907</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>904</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2078</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>26132</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>25670</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>94308</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>21013</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>20525</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>15439</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13404</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13165</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12749</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12266</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12124</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12091</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11852</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10943</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10800</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10722</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10721</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10680</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3118</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9016</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8881</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8857</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>700</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4284</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31370</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31357</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31272</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31236</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11487</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8489</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1183</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8467</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8461</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3102</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1483</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8361</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8346</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>957</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8143</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8128</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8113</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8103</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8102</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8095</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8081</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1049</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8021</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7970</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7966</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7909</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7859</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3301</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7854</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7840</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7819</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4684</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7809</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7807</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7771</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7726</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7681</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7583</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7517</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7515</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7497</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7471</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7422</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7406</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3037</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7321</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5324275</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7281</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7257</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7240</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>335</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7237</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7061</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7047</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6947</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3026</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6781</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>493570</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6650</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6643</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6584</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6568</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6567</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6560</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6540</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6278</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6276</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>263</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>887</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5147</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1732</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6028</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2331</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11011</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11005</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>527</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8063</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>379</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5281</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>69026</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6561</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8314</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7470</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7418</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>196</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8094</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8130</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3893</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>650</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>18177</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2969</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7245</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>444972</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>444266</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6569</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>261</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6333</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11534</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6227</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8794</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7505</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1017</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>180</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5284484</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8722</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5281576</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>62158</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7237</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6366</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7499</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7904</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1176</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6537</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8295</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8717</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6529</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7285</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6914</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6389</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6575</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6574</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12471</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6421</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10850</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5558</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5546</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5284469</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12484</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1140</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5505</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5284468</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2723790</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2723789</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8765</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2406</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7308</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5430</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2153</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10509</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5455</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>41478</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8028</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5284462</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31373</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6591</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1123</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2733525</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11289</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5344</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5327</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7216</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7922</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7276</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7501</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>643460</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>23665760</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>23668197</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>68289</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11972286</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5339</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5144</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11292</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>135398735</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>638034</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5054</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5770</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>22960</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7737</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4993</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1046</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>657298</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1030</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>62882</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2365</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4911</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5865</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5794</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6811</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7017</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16682730</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31217</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7935</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4781</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>676454</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8679</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4021</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5284441</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7108</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4764</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>996</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13266</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8691</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4754</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>992</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6720</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>991</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>54680782</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7579</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7526</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9074</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6838</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6124</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5921</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>14223</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>398</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7903</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6849</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6375</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6604200</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6587</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12302</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6108</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7195</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7416</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12076</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7048</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7475</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11769</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7444</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5111791</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4338370</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5447130</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7447</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>23668193</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8758</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>89594</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7057</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8640</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>15106</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16720</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6862</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>931</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4421</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2478</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>300</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4173</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>667493</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11910</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7059</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9280</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7055</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7002</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7567</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6344</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7543</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4130</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31426</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>135436526</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4156</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6658</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>15413</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4114</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9015</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4115</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>409301</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5284416</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>697993</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>460612</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>21954</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4004</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>15415</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>53232</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9903</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>299</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5280863</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>637796</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3776</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6557</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3767</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10958</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6374</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3715</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1923</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>785</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3639</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31222</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4943</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12332</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3598</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6214</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6478</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6901</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8127</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3589</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>320930</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>441140</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11164</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>753</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6466</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11057</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3463</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>370</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3440</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7362</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8029</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3385</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16562</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3346</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>23668198</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3314</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2758</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8343</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7641</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7720</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7833</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2723650</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>174</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7500</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12967</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6501</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6295</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7748</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>702</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3293</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3282</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2761171</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5991</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8815</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5757</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7834</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7835</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3224</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2724564</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1775</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6319</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11813</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1493</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10555</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6228</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6598</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6001</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>949</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6009</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6053</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7069</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5284385</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>13232</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>660</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2735009</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>448537</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8117</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2730</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3048</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>727200</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8268</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3039</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6564</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7206</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1486</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8449</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6365</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>642197</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11933</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7239</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6597</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11860</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7430</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5284381</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7839</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7280</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5889</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3017</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7261</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8560</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5743</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3036</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3035</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6294</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4211</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2955</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>15331</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>135398738</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9880</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7967</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>444041</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>135465076</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8445</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7610</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>323</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>61444</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>311</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2756</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2950</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>14012</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2727</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5284366</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6423</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8800</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>23392</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6212</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31296</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7964</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7812</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8805</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10757</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7260</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7255</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>22584</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7263</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7474</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6945</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>53665</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8266</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8371</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5959</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2708</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8630</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>289</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16724</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5943</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6854</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6129</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8480</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11236</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8606</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1548943</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2519</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>24633</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>18303</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>16043</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>31404</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7184</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8005</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2347</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10898</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6332</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6359</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7628</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>36383</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6623</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8115</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7095</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8425</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7503</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>244</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8785</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7367</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7220</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8447</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4650</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8400</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>243</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9223</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7111</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>241</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>240</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>35370</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2272</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2268</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>33557</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2265</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>65114</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9444</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>17170</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2256</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2244</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>134601</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>54670067</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>227</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2734956</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6115</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7541</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1549040</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>23565</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7102</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7340</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8341</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8486</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3417419</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>4984721</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3613389</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6702</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>28207</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5971</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7838</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7850</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7858</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>2087</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9570071</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>12364</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>457193</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7855</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6579</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>7847</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>8247</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>6342</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1989</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>1983</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>177</PCT-ID-List_uids_E>
                  </PCT-ID-List_uids>
                </PCT-ID-List>
              </PCT-QueryUids_ids>
            </PCT-QueryUids>
          </PCT-Download_uids>
          <PCT-Download_format value="smiles"/>
          <PCT-Download_compression value="gzip"/>
          <PCT-Download_use-3d value="false"/>
        </PCT-Download>
      </PCT-InputData_download>
    </PCT-InputData>
  </PCT-Data_input>
</PCT-Data>
