<?xml version="1.0"?>
<!DOCTYPE PCT-Data PUBLIC "-//NCBI//NCBI PCTools/EN" "http://pubchem.ncbi.nlm.nih.gov/pug/pug.dtd">
<PCT-Data>
  <PCT-Data_input>
    <PCT-InputData>
      <PCT-InputData_download>
        <PCT-Download>
          <PCT-Download_uids>
            <PCT-QueryUids>
              <PCT-QueryUids_ids>
                <PCT-ID-List>
                  <PCT-ID-List_db>pccompound</PCT-ID-List_db>
                  <PCT-ID-List_uids>
                    <PCT-ID-List_uids_E>70681521</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67616580</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70681537</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70681538</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70681539</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67889904</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70681540</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67617276</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67617223</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70681558</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67617590</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67617805</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67617657</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70683648</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70683649</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67607402</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67616823</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>9547801</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70685786</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>56965335</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>56965336</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67616088</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70685787</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67617339</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70685788</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67616256</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70685789</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67616724</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70687904</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70687914</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>56965231</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70687915</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70687916</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67607446</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67617538</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70687917</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70687918</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70689931</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67616238</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70689949</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70689950</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67615780</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70689951</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70689952</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67608654</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67616627</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70692104</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>11630056</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67616803</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67617933</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70692105</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70692106</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70692107</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70692108</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67607695</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67616712</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70694150</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70694151</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67615985</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67609322</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67616948</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67617592</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70694152</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>10266162</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70696276</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67616261</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70696277</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>67615890</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70696278</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70696279</PCT-ID-List_uids_E>
                  </PCT-ID-List_uids>
                </PCT-ID-List>
              </PCT-QueryUids_ids>
            </PCT-QueryUids>
          </PCT-Download_uids>
          <PCT-Download_format value="smiles"/>
          <PCT-Download_compression value="gzip"/>
          <PCT-Download_use-3d value="false"/>
        </PCT-Download>
      </PCT-InputData_download>
    </PCT-InputData>
  </PCT-Data_input>
</PCT-Data>
