<?xml version="1.0"?>
<!DOCTYPE PCT-Data PUBLIC "-//NCBI//NCBI PCTools/EN" "http://pubchem.ncbi.nlm.nih.gov/pug/pug.dtd">
<PCT-Data>
  <PCT-Data_input>
    <PCT-InputData>
      <PCT-InputData_download>
        <PCT-Download>
          <PCT-Download_uids>
            <PCT-QueryUids>
              <PCT-QueryUids_ids>
                <PCT-ID-List>
                  <PCT-ID-List_db>pccompound</PCT-ID-List_db>
                  <PCT-ID-List_uids>
                    <PCT-ID-List_uids_E>94391</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>3385</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73346427</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73346428</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73347930</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73347931</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73347932</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73347933</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73347934</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73349471</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73349472</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73349473</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73349474</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73349475</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73349476</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73349477</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73349478</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73351029</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73351030</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73351031</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73351032</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73351033</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73352510</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73352511</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73352512</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73353987</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73353988</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73355525</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73355526</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73355527</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73357063</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73357064</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>73357065</PCT-ID-List_uids_E>
                  </PCT-ID-List_uids>
                </PCT-ID-List>
              </PCT-QueryUids_ids>
            </PCT-QueryUids>
          </PCT-Download_uids>
          <PCT-Download_format value="smiles"/>
          <PCT-Download_compression value="gzip"/>
          <PCT-Download_use-3d value="false"/>
        </PCT-Download>
      </PCT-InputData_download>
    </PCT-InputData>
  </PCT-Data_input>
</PCT-Data>
