<?xml version="1.0"?>
<!DOCTYPE PCT-Data PUBLIC "-//NCBI//NCBI PCTools/EN" "http://pubchem.ncbi.nlm.nih.gov/pug/pug.dtd">
<PCT-Data>
  <PCT-Data_input>
    <PCT-InputData>
      <PCT-InputData_download>
        <PCT-Download>
          <PCT-Download_uids>
            <PCT-QueryUids>
              <PCT-QueryUids_ids>
                <PCT-ID-List>
                  <PCT-ID-List_db>pccompound</PCT-ID-List_db>
                  <PCT-ID-List_uids>
                    <PCT-ID-List_uids_E>64971</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>70678254</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127024873</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127024874</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127024875</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127024876</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127025477</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127025800</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127025801</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127025802</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127025803</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127026420</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127026421</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127026422</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127026726</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127027365</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127027366</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127027692</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127027693</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127027990</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127027991</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127028019</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127028020</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127028021</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127028307</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127028308</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127028309</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127028335</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127028336</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127028639</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127028966</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127028967</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127028968</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>127029258</PCT-ID-List_uids_E>
                  </PCT-ID-List_uids>
                </PCT-ID-List>
              </PCT-QueryUids_ids>
            </PCT-QueryUids>
          </PCT-Download_uids>
          <PCT-Download_format value="smiles"/>
          <PCT-Download_compression value="gzip"/>
          <PCT-Download_use-3d value="false"/>
        </PCT-Download>
      </PCT-InputData_download>
    </PCT-InputData>
  </PCT-Data_input>
</PCT-Data>
