<?xml version="1.0"?>
<!DOCTYPE PCT-Data PUBLIC "-//NCBI//NCBI PCTools/EN" "http://pubchem.ncbi.nlm.nih.gov/pug/pug.dtd">
<PCT-Data>
  <PCT-Data_input>
    <PCT-InputData>
      <PCT-InputData_download>
        <PCT-Download>
          <PCT-Download_uids>
            <PCT-QueryUids>
              <PCT-QueryUids_ids>
                <PCT-ID-List>
                  <PCT-ID-List_db>pccompound</PCT-ID-List_db>
                  <PCT-ID-List_uids>
                    <PCT-ID-List_uids_E>4843</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>5284373</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652665</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652669</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652984</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653127</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653128</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653279</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653431</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653715</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652828</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652831</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652832</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653278</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653433</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653580</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653712</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652666</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652668</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652827</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652985</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653436</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653437</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653713</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652662</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652667</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652830</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652983</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652987</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652988</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653435</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653577</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653710</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652829</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653280</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653281</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653432</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653434</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653576</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652825</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652986</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653711</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653714</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652826</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653130</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653582</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71652989</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653129</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653578</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653579</PCT-ID-List_uids_E>
                    <PCT-ID-List_uids_E>71653581</PCT-ID-List_uids_E>
                  </PCT-ID-List_uids>
                </PCT-ID-List>
              </PCT-QueryUids_ids>
            </PCT-QueryUids>
          </PCT-Download_uids>
          <PCT-Download_format value="smiles"/>
          <PCT-Download_compression value="gzip"/>
          <PCT-Download_use-3d value="false"/>
        </PCT-Download>
      </PCT-InputData_download>
    </PCT-InputData>
  </PCT-Data_input>
</PCT-Data>
